Feature/base templator and register
Lex-23/CryptoStockProject pull request #30
Opened 2021-12-30 14:51 UTC by Lex-23

2021-12-31 08:04 UTC, vadim-denisov requested changes

2021-12-31 08:04 UTC, vadim-denisov commented on cryptostock_api/cryptostock/notification/models.py
> +        return "Info".format(**data)
```suggestion
        return f"Event: {data}"
```

2021-12-31 08:04 UTC, vadim-denisov commented on cryptostock_api/cryptostock/notification/models.py
> +    pass
```suggestion
```

2021-12-31 08:04 UTC, vadim-denisov commented on cryptostock_api/cryptostock/notification/models.py
> +    get = classmethod(_templaters.get)
Should return `BaseTemplator`

2021-12-31 08:04 UTC, vadim-denisov commented on cryptostock_api/cryptostock/notification/models.py
> +            return templater_cls
```suggestion
            # TODO: register logic
            return templater_cls
```

2021-12-31 08:14 UTC, Lex-23 commented on cryptostock_api/cryptostock/notification/models.py
> +    get = classmethod(_templaters.get)
got it

2021-12-31 08:14 UTC, Lex-23 commented on cryptostock_api/cryptostock/notification/models.py
> +    pass
ok

2021-12-31 08:14 UTC, Lex-23 commented on cryptostock_api/cryptostock/notification/models.py
> +        return "Info".format(**data)
ok

2021-12-31 08:21 UTC, vadim-denisov requested changes

2021-12-31 08:21 UTC, vadim-denisov commented on cryptostock_api/cryptostock/notification/models.py
> +    get = classmethod(_templaters.get)
Should ALWAYS return BaseRegister

2021-12-31 08:21 UTC, vadim-denisov commented on cryptostock_api/cryptostock/notification/models.py
> +@TemplaterRegister.register(ConsumerType.TELEGRAM, NotificationEvent.SUCCESS_OFFER)
```suggestion
```

2021-12-31 08:53 UTC, vadim-denisov commented on cryptostock_api/cryptostock/notification/models.py
> +        return SENDER[self.type](message, **data)
```suggestion
    def send(self, **data):
        sender = SENDER.get(self.type)
        if sender is None:
            raise ValueError(f"Sender doesn't exist, type={self.type}")
        return sender(**data)
```
```

2021-12-31 09:00 UTC, vadim-denisov approved these changes

2021-12-31 09:01 UTC, merged

2022-01-04 08:11 UTC, Lex-23 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrading notification system](https://trello.com/c/rI1ECV4R/32-upgrading-notification-system)